name: GameHub Build Pipeline
on: [push]

jobs:
  mod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Tools
        run: |
          wget https://github.com/iBotPeaches/Apktool/releases/download/v2.9.3/apktool_2.9.3.jar -O apktool.jar
          wget https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar -O signer.jar
      - name: Decompile (Clean)
        run: |
          # Ескі папканы жойып, жаңадан ашамыз
          rm -rf workspace
          java -jar apktool.jar d gamehub.apk -f -o workspace
      - name: Inject Mod Menu
        run: |
          cp mod_menu.html workspace/assets/mod_menu.html
      - name: Rebuild & Sign
        run: |
          java -jar apktool.jar b workspace -o modded.apk
          java -jar signer.jar -a modded.apk --allowResign -o final/
      - uses: actions/upload-artifact@v4
        with:
          name: Modded-GameHub
          path: final/*.apk
